apiVersion: v1
kind: Pod
metadata:
  name: shell-operator
spec:
  containers:
    - name: shell-operator
      image: k8s.example.com/shell-operator:v1.0.0
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "128Mi"
          cpu: "200m"
  serviceAccountName: monitor-servicedeployments-acc
